### ISSUE TITLE
(BadMapError) expected a map, got: {:error, "\r\n# This file is in the public domain, ...

### ISSUE THREAD

**Issue by mathieuprog** [hrzndhrn/time_zone_info#5] opened 2020-03-29 04:44 UTC
Hello, when I try to run the benchmark:

>mix run bench/run.exs

I get the following error:

> ** (BadMapError) expected a map, got: {:error, "\r\n# This file is in the public domain, so clarified as 

[.....]
>     (time_zone_info 0.1.1) lib/time_zone_info/data_store/persistent_term.ex:82: TimeZoneInfo.DataStore.PersistentTerm.put_time_zone_info/1
>     (time_zone_info 0.1.1) lib/time_zone_info/data_store/persistent_term.ex:14: TimeZoneInfo.DataStore.PersistentTerm.put/1
>     bench/time_zone_database.exs:127: Bench.TimeZoneDatabase.setup_time_zone_info/0
>     bench/time_zone_database.exs:11: Bench.TimeZoneDatabase.run/0

**Comment by NickNeck** [comment] 2020-03-29 05:40
Hello,

that is an error from the `IanaParser`, but that is strange because in the tests the same code will run.
And I can not reproduce it. Do you get the same error with `mix test`?

**Comment by mathieuprog** [comment] 2020-03-29 05:54
Yes I have the same error when running `mix test`.

Note that I am on the master branch, and run on Windows 10.

`elixir --version` outputs:

> Erlang/OTP 22 [erts-10.7] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]
> 
> Elixir 1.10.2 (compiled with Erlang/OTP 21)

The first piece of string in the error is "\r\n", which is kinda specific to Windows; so it might be related to that?

**Comment by NickNeck** [comment] 2020-03-29 10:23
Thanks for your reporting and infos. Hopefully, it is fixed now.

**Closed as completed by NickNeck** 2020-03-29 10:23 UTC
